# Generated by Django 3.2.8 on 2023-03-05 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('recovery_description', models.CharField(max_length=200, null=True)),
                ('ticket_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('passengers', models.ManyToManyField(blank=True, related_name='passengers', to=settings.AUTH_USER_MODEL)),
                ('pilots', models.ManyToManyField(blank=True, related_name='pilots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
