# Generated by Django 3.2.8 on 2023-03-06 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230306_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers', models.ManyToManyField(blank=True, related_name='passengers', to=settings.AUTH_USER_MODEL)),
                ('pilots', models.ManyToManyField(blank=True, related_name='pilots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pilots',
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('exp_type', models.CharField(max_length=100, null=True)),
                ('launch_date', models.DateField()),
                ('available_spacecrafts', models.ManyToManyField(blank=True, related_name='available_vehicles', to='base.CurrentVehicle')),
            ],
        ),
        migrations.AddField(
            model_name='currentvehicle',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='base.vehicle'),
        ),
    ]
