# Generated by Django 3.2.8 on 2023-03-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230306_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvehicle',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship', to='base.vehicle'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('date_purchased', models.DateField()),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='base.currentvehicle')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tickets_purchased',
            field=models.ManyToManyField(blank=True, related_name='tickets_purchased', to='base.Ticket'),
        ),
    ]
