# Generated by Django 3.2.8 on 2023-03-06 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230306_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='available_spacecrafts',
        ),
        migrations.AddField(
            model_name='currentvehicle',
            name='expedition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedition', to='base.expedition'),
        ),
    ]
