# Generated by Django 3.2.8 on 2023-03-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230316_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentvehicle',
            name='seats',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
