# Generated by Django 3.2.8 on 2023-03-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20230317_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tickets_purchased',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tics', models.ManyToManyField(blank=True, related_name='tics', to='base.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='base.OrderItem'),
        ),
    ]
