# Generated by Django 3.2.8 on 2023-03-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20230317_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='exp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exp', to='base.expedition'),
        ),
    ]
