# Generated by Django 3.2.8 on 2023-03-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_orderitem_vehi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentvehicle',
            name='passengers',
        ),
        migrations.AddField(
            model_name='currentvehicle',
            name='passengers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
