# Generated by Django 3.2.8 on 2023-03-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
    ]
