# Generated by Django 3.2.8 on 2023-03-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20230318_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='modules', to='base.Module'),
        ),
    ]
