# Generated by Django 3.2.8 on 2023-03-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_user_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mod_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
