# Generated by Django 3.2.8 on 2023-03-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_question_mod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='max_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
